file_format: "1"
id: companion-totem
name: COMPANION-TOTEM
type: shield
url: https://github.com/GEIGEIGEIST/TOTEM
requires: [seeeduino_xiao_ble]
features:
  - keys
siblings:
  - companion-totem_left
  - companion-totem_right
